"""empty message

Revision ID: 60a0ecc6ce37
Revises: cef3414be22a
Create Date: 2023-09-26 19:29:30.406621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a0ecc6ce37'
down_revision = 'cef3414be22a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.ARRAY(sa.String()), nullable=True))

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('genre')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
